tags:
  - name: Blogs
    description: API for managing blogs

paths:
  /api/blogs:
    get:
      summary: Get a list of all blogs
      tags: [ Blogs ]
      security: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlogViewModel'
    post:
      summary: Add a new blog
      tags: [ Blogs ]
      security:
        - basicAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInputModel'
      responses:
        201:
          description: The blog was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogViewModel'
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        401:
          description: Unauthorized

  /api/blogs/{id}:
    get:
      summary: Get a blog by ID
      tags: [ Blogs ]
      security: [ ]
      parameters:
        - in: path
          name: id
          required: true
          description: "The unique identifier of the blog"
          schema:
            type: integer
            example: 2
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogViewModel'
        404:
          description: Not found
    put:
      summary: Update a blog by ID
      tags: [ Blogs ]
      security:
        - basicAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          description: "The unique identifier of the blog"
          schema:
            type: integer
            example: 2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInputModel'
      responses:
        204:
          description: No Content
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        401:
          description: Unauthorized
        404:
          description: Not Found
    delete:
      summary: Delete a blog by ID
      tags: [ Blogs ]
      parameters:
        - in: path
          name: id
          required: true
          description: "The unique identifier of the blog"
          schema:
            type: integer
            example: 2
      responses:
        204:
          description: No Content
        401:
          description: Unauthorized
        404:
          description: Not found
components:
  schemas:
    BlogViewModel:
      type: object
      required:
        - id
        - name
        - description
        - websiteUrl
      properties:
        id:
          type: string
          description: "The unique identifier for the blog"
          example: "1"
        name:
          type: string
          description: "The name of the blog"
          example: "Tom Rider"
        description:
          type: string
          description: "The blog's description"
          example: "New life"
        websiteUrl:
          type: string
          description: "Link to blog's web site"
          example: "https://samurai.io"
    BlogInputModel:
      type: object
      required:
        - name
        - description
        - websiteUrl
      properties:
        name:
          type: string
          description: "The name of the blog"
          example: "Tom Rider"
        description:
          type: string
          description: "The blog's description"
          example: "New life"
        websiteUrl:
          type: string
          description: "Link to blog's web site"
          example: "https://samurai.it-incubator.io"
    ValidationError:
      type: object
      properties:
        field:
          type: string
          example: "name"
        message:
          type: string
          example: "Invalid name"
    ValidationErrorResponse:
      type: object
      properties:
        errorsMessages:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'